{{- $name := "validate-http-probes" }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  labels:
    labels: {{ include "kyverno-policies.labels" . | nindent 4 }}
  name: {{ $name }}
  annotations:
    policies.kyverno.io/minversion: 1.3.6
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
spec:
  {{- with index .Values "validationFailureActionByPolicy" $name }}
  validationFailureAction: {{ toYaml . }}
  background: {{ .Values.background }}
  rules:
  - name: validate-probe-handles
    match:
      resources:
        kinds:
        - Pod
    {{- with merge (index .Values "policyExclude" "check-runasgroup") (index .Values "policyExclude" $name) }}
    exclude:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with merge (index .Values "policyPreconditions" "check-runasgroup") (index .Values "policyPreconditions" $name) }}
    preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    validate:
      message: "probes with /healthz and /readyz handles required"
      pattern:
        spec:
          containers:
          - livenessProbe:
              periodSeconds: ">0"
              httpGet:
                port: "8080"
                scheme: "HTTP"
                path: "/healthz"
          - readinessProbe:
              periodSeconds: ">0"
              httpGet:
                port: "8080"
                scheme: "HTTP"
                path: "/readyz"
{{- end }}
